esphome:
  name: esp01s-zonnescherm

esp8266:
  board: esp01_1m

logger:
  level: INFO

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  power_save_mode: none
  min_auth_mode: WPA2
  fast_connect: True
  reboot_timeout: 90s
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap:
    ssid: "esphome-zonnescherm"
    password: ""

captive_portal:

globals:
  - id: invert_dir
    type: bool
    restore_value: yes
    initial_value: 'false'

switch:
  - platform: template
    id: invert_switch
    name: "Awning invert direction"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(invert_dir) = true;'
    turn_off_action:
      - lambda: 'id(invert_dir) = false;'

  - platform: gpio
    id: relay_up
    name: "Awning Up (relay)"
    pin: { number: GPIO0, inverted: true }
    restore_mode: ALWAYS_OFF
    interlock: [relay_down]
    interlock_wait_time: 500ms
    entity_category: diagnostic
    disabled_by_default: true

  - platform: gpio
    id: relay_down
    name: "Awning Down (relay)"
    pin: { number: GPIO2, inverted: true }
    restore_mode: ALWAYS_OFF
    interlock: [relay_up]
    interlock_wait_time: 500ms
    entity_category: diagnostic
    disabled_by_default: true

button:
  - platform: restart
    name: "Reboot"

  - platform: template
    name: "Up/Stop"
    id: up_stop_btn
    on_press:
      - if:
          condition:
            lambda: 'return id(awning).current_operation == COVER_OPERATION_OPENING;'
          then:
            - cover.stop: awning
          else:
            - cover.open: awning

  - platform: template
    name: "Down/Stop"
    id: down_stop_btn
    on_press:
      - if:
          condition:
            lambda: 'return id(awning).current_operation == COVER_OPERATION_CLOSING;'
          then:
            - cover.stop: awning
          else:
            - cover.close: awning

cover:
  - platform: time_based
    id: awning
    name: "Awning"
    device_class: awning

    open_action:
      - if:
          condition:
            lambda: 'return !id(invert_dir);'
          then:
            - switch.turn_on: relay_up
          else:
            - switch.turn_on: relay_down

    close_action:
      - if:
          condition:
            lambda: 'return !id(invert_dir);'
          then:
            - switch.turn_on: relay_down
          else:
            - switch.turn_on: relay_up

    stop_action:
      - switch.turn_off: relay_up
      - switch.turn_off: relay_down

    open_duration: 40s   # adjust to your motor's measured travel time
    close_duration: 38s  # adjust to your motor's measured travel time
